modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Eladkay/Scanner/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Eladkay the original creator of the mod. IGCBOOM & Misterplus for porting the mod to more recent versions. Picono435 for the latest port." #optional
authors="${mod_authors}"

description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="ftblibrary"
mandatory=true
versionRange="[1605.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="ftbchunks"
mandatory=false
versionRange="[1605.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="ftbteams"
mandatory=false
versionRange="[1605.2,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="crafttweaker"
mandatory=false
versionRange="[${crafttweaker_version},)"
ordering="NONE"
side="SERVER"